---
title: "collaborator-analysis"
format: html
editor: visual
authors: Gabriella C., Jorge C.
---

## Excercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)
```

```{r}
lobster_traps <- read_csv(here::here("data-gabriella-jorge/Lobster_Trap_Counts_All_Years_20210519.csv"))
```
```{r}
colnames(lobster_traps)
head(lobster_traps)
```

```{r}
lobster_traps <- lobster_traps %>% 
    mutate(TRAPS = na_if(TRAPS, -99999))
unique(lobster_traps)
```

```{r}
not_napl <- lobster_traps %>% 
  filter(SITE != "NAPL")
```

```{r}
carp_20_traps <- lobster_traps %>% 
    filter(SITE == "CARP" & TRAPS > 20)
```

```{r}
max_lobster_traps <- lobster_traps %>% 
    group_by(SITE, MONTH) %>%
    summarize(MAX_TRAPS = max(TRAPS, na.rm = TRUE))
```
## Excercise: Data Visualization

```{r}
ggplot(data = lobster_traps, aes(x = TRAPS)) +
    geom_histogram() +
    facet_wrap( ~ YEAR)
```

```{r}
lobsters_traps_summarize <- lobster_traps %>% 
  group_by(SITE, YEAR) %>% 
  summarize(TOTAL_TRAPS = sum(TRAPS, na.rm = TRUE))
```
```{r}
# line plot
ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS)) +
    geom_line(aes(color = SITE))

# line and point plot
ggplot(data = lobsters_traps_summarize, aes(x = YEAR, y = TOTAL_TRAPS)) +
    geom_point(aes(color = SITE)) +
    geom_line(aes(color = SITE))
```
```{r}
lobster_traps_fishing_pressure <- lobster_traps %>% 
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(FISHING_PRESSURE = if_else(TRAPS >= 8, true = "high", false = "low")) %>%
    group_by(SITE, FISHING_PRESSURE) %>%
    summarize(COUNT = n()) %>%
    drop_na()

# bar plot
ggplot(data = lobster_traps_fishing_pressure, aes(x = SITE, y = COUNT, fill = FISHING_PRESSURE)) +
    geom_col() +
  labs(
    x = "site",
    y = "Trap Count",
    fill = "Fishing Pressure",
    title = "Lobster Traps by site"
  ) +
  theme_light() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )

# dodged bar plot
ggplot(data = lobster_traps_fishing_pressure, 
       aes(x = SITE, y = COUNT, fill = FISHING_PRESSURE)) +
  geom_col(position = "dodge") +
  labs(
    x = "Site",
    y = "Trap Count",
    fill = "Fishing Pressure",
    title = "Lobster Traps by Site"
  ) +
  theme_light() +
  theme(
    axis.text.x = element_text(angle = 90, hjust = 1)
  )
```

