---
title: "gabriella-analysis"
format: html
editor: visual
authors: Gabriella Chavez (owner), Jorge Coronado (collaborator)
---

## Exercise: Explore, Clean, and Wrangle Data

```{r}
library(readr)
library(dplyr)
library(ggplot2)
library(tidyr)
library(here)

lobster_abundance <- read_csv(here::here("data-gabriella-jorge/Lobster_Abundance_All_Years_20220829.csv"))
```

```{r}
lobster_abundance <- lobster_abundance %>% 
    mutate(SIZE_MM = na_if(SIZE_MM, -99999))

```

```{r}
not_napl <- lobster_abundance %>% 
    filter(SITE != "NAPL")
```

```{r}
aque_70mm <- lobster_abundance %>% 
    filter(SITE == "AQUE" & SIZE_MM >= 70)
```

```{r}
# `group_by() %>% summarize()` practice

max_lobster <- lobster_abundance %>% 
  group_by(SITE, MONTH) %>% 
  summarize(MAX_LENGTH = max(SIZE_MM, na.rm = TRUE))
```

## Exercise: Data Visualization

```{r}
ggplot(data = lobster_abundance, 
       aes(x = SIZE_MM)) +
    geom_histogram(fill = "steelblue", color = "white", bins = 20) +
    facet_wrap(~SITE) +
    labs(
        title = "Lobster Size Distribution by Site",
        x = "Size (mm)",
        y = "Count"
    ) +
    theme_light() +
    theme(
        axis.title.y = element_text(size = 12),
        plot.background = element_rect(fill = "gray95"),
        panel.grid.major = element_line(linetype = "dashed")
    )
```

```{r}
lobsters_summarize <- lobster_abundance %>% 
  group_by(SITE, YEAR) %>% 
  summarize(COUNT = n())

# line plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_line(aes(color = SITE), linewidth = 1) +
  labs(
    title = "Lobster Counts Over Time by Site",
    x = "Year",
    y = "Count",
    color = "Site"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed"),
    axis.text.x = element_text(angle = 90, hjust = 1)
  ) +
  scale_x_continuous(
    breaks = seq(min(lobsters_summarize$YEAR),
                 max(lobsters_summarize$YEAR),
                 by = 1)
  )

# line and point plot
ggplot(data = lobsters_summarize, aes(x = YEAR, y = COUNT)) +
  geom_point(aes(color = SITE), size = 2, alpha = 0.8) +
  geom_line(aes(color = SITE), linewidth = 1) +
  labs(
    title = "Lobster Counts Over Time by Site",
    x = "Year",
    y = "Count",
    color = "Site"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed"),
    axis.text.x = element_text(angle = 90, hjust = 1)
  ) +
  scale_x_continuous(
    breaks = seq(min(lobsters_summarize$YEAR),
                 max(lobsters_summarize$YEAR),
                 by = 1)
  )

```

```{r}
lobster_size_lrg <- lobster_abundance %>%
    filter(YEAR %in% c(2019, 2020, 2021)) %>%
    mutate(SIZE_BIN = if_else(SIZE_MM <= 70, true = "small", false = "large")) %>%
    group_by(SITE, SIZE_BIN) %>%
    summarize(COUNT = n()) %>%
    drop_na()
```

```{r}
# bar plot
p1 <- ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
  geom_col(color = "black") +
  labs(
    title = "Lobster Size Distribution by Site",
    x = "Site",
    y = "Count",
    fill = "Size Category"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  )

p1

ggsave(
  filename = here::here("figs-gabriella-jorge", "lobster_bar_plot.png"),
  plot = p1,
  width = 6,
  height = 4
)


# dodged bar plot
p2 <- ggplot(data = lobster_size_lrg, aes(x = SITE, y = COUNT, fill = SIZE_BIN)) +
  geom_col(position = "dodge", color = "black") +
  labs(
    title = "Lobster Size Distribution by Site",
    x = "Site",
    y = "Count",
    fill = "Size Category"
  ) +
  theme_light() +
  theme(
    plot.title = element_text(hjust = 0.5),
    panel.grid.major = element_line(linetype = "dashed"),
    axis.text.x = element_text(angle = 45, hjust = 1)
  ) +
  scale_fill_brewer(palette = "Set2")

p2

ggsave(
  filename = here::here("figs-gabriella-jorge", "lobster_dodged_bar_plot.png"),
  plot = p2,
  width = 6,
  height = 4
)

```
